name: Provision User in Fortify on Demand

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to provision'
        required: true
      email:
        description: 'Email of the user'
        required: true
      fName:
        description: 'User First Name'
        required: true
      lName:
        description: 'User Last Name'
        required: true
      role:
        description: 'Role to assign to the user'
        required: true
jobs:
  provision-user:
    runs-on: ubuntu-latest
    steps:
      - name: Provision User in Fortify on Demand
        env:
          FOD_API_TOKEN: ${{ secrets.FOD_API_TOKEN }}
      - name: Get Access Token
        id: get-token
        run: |
          response=$(curl -s -X POST "https://api.fed.fortify.com/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.FOD_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.FOD_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          echo "access_token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Create User in Fortify On-Demand
        run: |
          curl -X POST https://api.fed.fortify.com/api/v3/users \
          -H "Authorization: Bearer ${{ env.access_token }}" \
          -H "Content-Type: application/json" \
          -d '{
                "userName": "newuser-test",
                "email": "newuser@test.com",
                "firstName": "New",
                "lastName": "User",
                "roleIds": [1128]
              }'
