name: Provision User in Fortify on Demand

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to provision'
        required: true
      email:
        description: 'Email of the user'
        required: true
      fName:
        description: 'User First Name'
        required: true
      lName:
        description: 'User Last Name'
        required: true
      role:
        description: 'Role to assign to the user'
        required: true
jobs:
  provision-user:
    runs-on: ubuntu-latest
    steps:
      - name: Provision User in Fortify on Demand
        env:
          FOD_API_TOKEN: ${{ secrets.FOD_API_TOKEN }}
        run: |
          # Step 1 & 2 : Create a new user in Fortify on Demand and Assign Role
          curl -X POST https://api.fed.fortifygov.com/api/v3/users \
          -H "Authorization: Bearer $FOD_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "userName": "${{ github.event.inputs.username }}",
            "email": "${{ github.event.inputs.email }}",
            "firstName": "${{ github.event.inputs.fName }}",
            "lastName": "${{ github.event.inputs.lName }}",
            "roleIds": ${{ github.event.inputs.role }}
          }'
