name: Provision User in Fortify on Demand

on:
  workflow_dispatch:

jobs:
  provision-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Access Token
        id: get-token
        run: |
          response=$(curl -s -X POST "https://api.fed.fortifygov.com/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "scope=api-tenant" \
            -d "client_id=${{ secrets.FOD_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.FOD_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          echo "access_token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Create User in Fortify On-Demand
        run: |
          curl -X POST https://api.fed.fortifygov.com/api/v3/users \
          -H "Authorization: Bearer ${{ env.access_token }}" \
          -H "Content-Type: application/json" \
          -d '{
                "userName": "newuser-test",
                "email": "newuser@test.com",
                "firstName": "New",
                "lastName": "User",
                "roleIds": [1128]
              }'
