name: Fortify On-Demand Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fortify-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ScanCentral Client
        run: |
          # Use the correct URL from a cloud storage service like AWS S3
          wget -O Fortify_ScanCentral_Client_Latest_x64.zip "https://fod-tools.s3.us-east-1.amazonaws.com/Fortify_ScanCentral_Client_Latest_x64.zip?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEMX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIHl%2FvwsCOAB5zRJQz94EcHVE0WHCS%2BjOIeZTRmCY0NnCAiEAqrgnSCYyEJgy6J7pEg1xLqa27qfjlZ0ksWtu3XNIAbsq5QMITRAFGgw2Mjc1NjY4OTQzOTkiDGX0heFobO1Nm3L0mSrCAyCxMRys6kyg07fcLed8EeZ3w5qhzpP6my9Gmaj4PCXWiiT4JDmzpAf%2F%2FxAGBFfVaeVHT8EPnU8paAABZ8xSRD6n0CRBC72uQ9VrOP2WMhkxvDYcz0Wz1oc8mFoaBb8LcLp9kZtbiY%2BMWm%2BIev%2Fhy0idw80zrjEYEIPj9iL6gGfgCIGiDEnFxWbw%2FVq6X5rhCZFJMcCCsIIgOrEl1e%2B5LSpdie4u5DvOjqCuGYM3u0hui65ChEZJfkDpFS9QiEgdGp%2Fo8UjI94ARNy98uk5GF0sJpUOL%2FKfvyizYDyU%2FgbzuyOhTLFEp%2FF0ryyWFtVN6TAYUoJ6M39esQJZtCeqpT11Vr%2Bc6K4sHhRCiwO33wzUTyxlimfuBSWRzYEOpAdJbOrRR8rGrQracXIFNnX8LspJ1jAlDkuZPJh77ll1l90hWynuvZN742HW3p7Tyf%2BO0mHTmRQIwb%2FKaEj6gcYMGv0YT8vC8EoM72Yuvsxv8i3trKGxeSGbjrBp4euuh8XhxvGOP90nqEdhlP7CvD7khvDHelICwR7itVx2qIHFZ4QP8xHzt3h9%2F%2Bku1tLhQ5Zs3AEzECbIMH5YZe6%2FHzOtpMSi3%2BjC7v7S5Bjq8As0y5U177G2eMWAHdIFRhDmZ8wbgnA8sW7n9Er%2BT8kZg4B518XQaXInfWGOlFAy%2BIGnM9da07yg93nedSjy4Oot1hGbEQ8kdemFbCAVFDBgMrjxv2yfzOs0KgYw4QtQR9Ca5YCj7Z9GRThu0qKTa89MoOfBnV4ym7agkjJG3eyfn9omCwq5U6w5%2Fp9lRFxca1NRo2XNAk%2BSOS2oAWPR6gIzx6PeFFq4x6apgD8E2p4J3N5h6Oo8p7GGdQZxZp8MOk3rK0ZGz%2FYbqsMzrhWZwkGL2tgJ%2Bmr7uDzjnU7mEQmHNZ8zuKpbCj2iTkpSpLCDxk4iZKjgppe99PMpdkVF4r4KaD54%2BOJ2IX%2Bxcw7aLZaaZka1Hy%2BYISHa6jRSymNcsYUzGwPGvkXdwdCNJhG8HFOq37uJTzykyunHrUMY%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAZEHPG3U7ZHPWMZPJ%2F20241107%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241107T202150Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=0e26d5db927d0c8a2d75d099c101b70587f070fecde4f428463d58e873f78952"
          unzip Fortify_ScanCentral_Client_Latest_x64.zip -d $(pwd)/scancentral-client
          export PATH=$PATH:$(pwd)/scancentral-client/bin
          
      
      - name: Run ScanCentral Command
        run: |
          # Use the pre-installed ScanCentral Client to package the source code
          scancentral package -bt none -b none -o "mycode.zip"
          # -bt: Build tool (e.g., mvn, gradle, npm)
          # -b: Build command to compile your project
          # -o: Output file for the packaged source code

      - name: Get Access Token
        id: get-token
        run: |
          response=$(curl -s -X POST "https://api.fed.fortifygov.com/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.FOD_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.FOD_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          echo "access_token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Upload .zip File for Scanning
        run: |
          curl -X POST "https://api.fed.fortifygov.com/api/v3/releases/{releaseId}/scan-uploads" \
            -H "Authorization: Bearer ${{ env.access_token }}" \
            -H "FOD-Tenant: ${{ secrets.FOD_TENANT_ID }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@mycode.zip" \
            -F "scanSettingsId={scanSettingsId}" \
            -F "isBundledAssessment=false"

      - name: Start Scan
        run: |
          curl -X POST "https://api.fed.fortifygov.com/api/v3/releases/{releaseId}/scans" \
            -H "Authorization: Bearer ${{ env.access_token }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "scanType": "Static",
                  "entitlementPreferenceType": "SingleScan",
                  "scanSettingsId": {scanSettingsId}
                }'
