name: Fortify On-Demand Scan

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      releaseId:
        description: 'Release ID'
        required: true

jobs:
  fortify-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Package source code
        uses: fortify/github-action/package@v1
        env:
          PACKAGE_EXTRA_OPTS: -oss -bt none 
          # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip

      - name: Get Access Token
        id: get-token
        run: |
          response=$(curl -s -X POST "https://api.fed.fortifygov.com/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.FOD_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.FOD_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          echo "access_token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Upload .zip File for Scanning
        run: |
          curl -X POST "https://api.fed.fortifygov.com/api/v3/releases/${{ github.event.inputs.releaseId }}/scan-uploads" \
            -H "Authorization: Bearer ${{ env.access_token }}" \
            -H "FOD-Tenant: ${{ secrets.FOD_TENANT_ID }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@package.zip" \
            -F "scanSettingsId={scanSettingsId}" \
            -F "isBundledAssessment=false"

      - name: Start Scan
        run: |
          curl -X POST "https://api.fed.fortifygov.com/api/v3/releases/${{ github.event.inputs.releaseId }}/scans" \
            -H "Authorization: Bearer ${{ env.access_token }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "scanType": "Static",
                  "entitlementPreferenceType": "SingleScan",
                  "scanSettingsId": {scanSettingsId}
                }'
