name: Fortify On-Demand Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fortify-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ScanCentral Client
        run: |
          # Use the correct URL from a cloud storage service like AWS S3
          wget https://fod-tools.s3.us-east-1.amazonaws.com/Fortify_ScanCentral_Client_Latest_x64.zip-O scancentral-client.zip
          unzip scancentral-client.zip -d scancentral-client
          export PATH=$PATH:$(pwd)/scancentral-client/binfod
          
      
      - name: Run ScanCentral Command
        run: |
          # Use the pre-installed ScanCentral Client to package the source code
          scancentral package -bt none -b none -o "mycode.zip"
          # -bt: Build tool (e.g., mvn, gradle, npm)
          # -b: Build command to compile your project
          # -o: Output file for the packaged source code

      - name: Get Access Token
        id: get-token
        run: |
          response=$(curl -s -X POST "https://api.fed.fortifygov.com/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.FOD_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.FOD_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          echo "access_token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Upload .zip File for Scanning
        run: |
          curl -X POST "https://api.fed.fortifygov.com/api/v3/releases/{releaseId}/scan-uploads" \
            -H "Authorization: Bearer ${{ env.access_token }}" \
            -H "FOD-Tenant: ${{ secrets.FOD_TENANT_ID }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@mycode.zip" \
            -F "scanSettingsId={scanSettingsId}" \
            -F "isBundledAssessment=false"

      - name: Start Scan
        run: |
          curl -X POST "https://api.fed.fortifygov.com/api/v3/releases/{releaseId}/scans" \
            -H "Authorization: Bearer ${{ env.access_token }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "scanType": "Static",
                  "entitlementPreferenceType": "SingleScan",
                  "scanSettingsId": {scanSettingsId}
                }'
